# 10 Minutes of Pandas
- importing
- Data Structure
- date_range()
- pd.Series()
- pd.DataFrame()
<br></br>
- df.dtypes
- df.index
- df.head()
- df.tail()
- df.describe()
- df.index
- df.to_numpy()
- df.T
- df.sort_index()
- df.sort_values('col_name')
<br></br>
__SELECT__
- df['col_name']
- df[0:3]
- df[df['pay'] > 30000]
<br></br>
- df.loc['row', 'col']
- df.loc[(condition) & (condition)]
- df.at['row', 'col']
<br></br>
__SETTING__
- df.at['row', 'col'] = 20
- df.loc['row', 'col'] = "sunyog"
<br></br>
__WHERE__
- no need to specify rows when using a condition.
- df.loc[(condition) | (condition), 'col'] = "value"
- df2.loc[(df2.loc[:, 'pay'] > 30000) & (df2.loc[:, 'gender'] == 'Male'), 'name'] = "Hari"
    - Set name = "Hari" of the row containing pay > 30000 AND gender = 'Male'. 
<br></br>
- Missing Data
- Merge
- concat
- grouping

## Importing pandas

In [1]:
import numpy as np
import pandas as pd

## Basic Data Structure in Pandas
- __Series__: one-dimensional labeled array holding data of any type.
- __DataFrame__: two-dimensional data structure that holds data like a two-dimensional array or a table with rows and columns.

In [2]:
s = pd.Series([1, 2, 3, 4, np.nan, 6, 8])
print(s)

0    1.0
1    2.0
2    3.0
3    4.0
4    NaN
5    6.0
6    8.0
dtype: float64

__date_range() takes a date and period as input and return list of 'period' number of dates from date to specific date.__

In [3]:
dates = pd.date_range("20181120", periods=6)
print(dates)

DatetimeIndex(['2018-11-20', '2018-11-21', '2018-11-22', '2018-11-23',
               '2018-11-24', '2018-11-25'],
              dtype='datetime64[ns]', freq='D')

__passing a dictionary of objects in DataFrame where the "keys" are the "column labels" and the "values" are the "column values".__

In [4]:
df = pd.DataFrame({
    'employee_id':np.arange(0,5, dtype='int8'),
    'name':["Rahul", "Vaishnavi", "Amrit", "Ravi", "Vanshika"],
    'gender':pd.Categorical(["Male", "Female", "Male", "Male", "Female"]),
    'experience':[2, 3, 1, 4, 7],
    'pay':[23000, 27000, 17000, 36000, 64000]
})
print(df.head(), "\n")
print(df.tail())

   employee_id       name  gender  experience    pay
0            0      Rahul    Male           2  23000
1            1  Vaishnavi  Female           3  27000
2            2      Amrit    Male           1  17000
3            3       Ravi    Male           4  36000
4            4   Vanshika  Female           7  64000

   employee_id       name  gender  experience    pay
0            0      Rahul    Male           2  23000
1            1  Vaishnavi  Female           3  27000
2            2      Amrit    Male           1  17000
3            3       Ravi    Male           4  36000
4            4   Vanshika  Female           7  64000

In [5]:
df2 = pd.DataFrame(
    [['sunyog', 15, 7], ['suyog', 16, 9], ['saurabh', 16, 8]], 
    columns = ['name', 'age', 'grade'], 
    index = [1, 2, 3])

df2.head()

      name  age  grade
1   sunyog   15      7
2    suyog   16      9
3  saurabh   16      8

__DataFrame.dtypes returns the type of values that each column is holding.__

In [6]:
print(df.dtypes)

employee_id        int8
name             object
gender         category
experience        int64
pay               int64
dtype: object

__Probably returns the range() of columns.__

In [7]:
df.index

RangeIndex(start=0, stop=5, step=1)

__DataFrame.columns returns the list of columns a dataframe contains.__

In [8]:
df.columns

Index(['employee_id', 'name', 'gender', 'experience', 'pay'], dtype='object')

__DataFrame.to_numpy() converts a DataFrame into a numpy array, where a single array contains the row of a DataFrame.__

In [9]:
df.to_numpy()

array([[0, 'Rahul', 'Male', 2, 23000],
       [1, 'Vaishnavi', 'Female', 3, 27000],
       [2, 'Amrit', 'Male', 1, 17000],
       [3, 'Ravi', 'Male', 4, 36000],
       [4, 'Vanshika', 'Female', 7, 64000]], dtype=object)

__Desribes the statistics of a DataFrame. (statistics of columns that contains numeric values)__

In [10]:
df.describe()

       employee_id  experience           pay
count     5.000000    5.000000      5.000000
mean      2.000000    3.400000  33400.000000
std       1.581139    2.302173  18447.222013
min       0.000000    1.000000  17000.000000
25%       1.000000    2.000000  23000.000000
50%       2.000000    3.000000  27000.000000
75%       3.000000    4.000000  36000.000000
max       4.000000    7.000000  64000.000000

__DataFrame.T Transposes the dataframe__

In [11]:
df.T

                 0          1      2      3         4
employee_id      0          1      2      3         4
name         Rahul  Vaishnavi  Amrit   Ravi  Vanshika
gender        Male     Female   Male   Male    Female
experience       2          3      1      4         7
pay          23000      27000  17000  36000     64000

__DataFrame.head() returns the first 6 element of a DataFrame.__

In [12]:
df.head()

   employee_id       name  gender  experience    pay
0            0      Rahul    Male           2  23000
1            1  Vaishnavi  Female           3  27000
2            2      Amrit    Male           1  17000
3            3       Ravi    Male           4  36000
4            4   Vanshika  Female           7  64000

__DataFrame.sort_index() sorts the DataFrame on the basis of column names.__

In [13]:
df.sort_index(axis=1, ascending=True)

   employee_id  experience  gender       name    pay
0            0           2    Male      Rahul  23000
1            1           3  Female  Vaishnavi  27000
2            2           1    Male      Amrit  17000
3            3           4    Male       Ravi  36000
4            4           7  Female   Vanshika  64000

__DataFrame.sort_values('col_name') sorts the body of DataFrame on the basis of specific column.__

In [14]:
df.sort_values('name')

   employee_id       name  gender  experience    pay
2            2      Amrit    Male           1  17000
0            0      Rahul    Male           2  23000
3            3       Ravi    Male           4  36000
1            1  Vaishnavi  Female           3  27000
4            4   Vanshika  Female           7  64000

## Selection
- Accessing values in dataframe.

__df['col_name']__ returns the values  stored under a specified column.

In [15]:
df['name']

0        Rahul
1    Vaishnavi
2        Amrit
3         Ravi
4     Vanshika
Name: name, dtype: object

__df[n:m]__ returns specific parts of the dataframe.
- from __nth__ row to __mth__ row.
- Note that contrary to usual python slices, both the start and the stop are included.

In [16]:
df[0:3]

   employee_id       name  gender  experience    pay
0            0      Rahul    Male           2  23000
1            1  Vaishnavi  Female           3  27000
2            2      Amrit    Male           1  17000

In [17]:
df.head()

   employee_id       name  gender  experience    pay
0            0      Rahul    Male           2  23000
1            1  Vaishnavi  Female           3  27000
2            2      Amrit    Male           1  17000
3            3       Ravi    Male           4  36000
4            4   Vanshika  Female           7  64000

__Boolean Indexing__

In [18]:
df[df['pay'] > 27000]

   employee_id      name  gender  experience    pay
3            3      Ravi    Male           4  36000
4            4  Vanshika  Female           7  64000

### df.loc(row, column)
- rows and columns can be __interger__, __string__, __booleans__, __list [x, y, z]__ or __slice [x:y].__

In [19]:
df.loc[1, 'name']

'Vaishnavi'

In [20]:
df.loc[[1, 2], ['name', 'gender']]

        name  gender
1  Vaishnavi  Female
2      Amrit    Male

In [21]:
df.loc[1:3, ['name', 'experience', 'pay']]

        name  experience    pay
1  Vaishnavi           3  27000
2      Amrit           1  17000
3       Ravi           4  36000

In [22]:
df.loc[1:3, 'employee_id':'gender']

   employee_id       name  gender
1            1  Vaishnavi  Female
2            2      Amrit    Male
3            3       Ravi    Male

In [23]:
# returns row as series
df.loc[1]

employee_id            1
name           Vaishnavi
gender            Female
experience             3
pay                27000
Name: 1, dtype: object

In [24]:
df.loc[[False, True, False, True, False]]
df[[False, True, False, True, False]]

   employee_id       name  gender  experience    pay
1            1  Vaishnavi  Female           3  27000
3            3       Ravi    Male           4  36000

using __conditionals__ with df.loc[]
- __df.loc[(condition), column]__
    - Get the data in __column__ for the __row__ on which the __condition__ is __true.__

In [25]:
df.loc[df['pay'] > 30000]

   employee_id      name  gender  experience    pay
3            3      Ravi    Male           4  36000
4            4  Vanshika  Female           7  64000

In [26]:
df.loc[(df['pay'] > 30000) & (df['experience'] > 4)]

   employee_id      name  gender  experience    pay
4            4  Vanshika  Female           7  64000

In [27]:
df.loc[(df['pay'] > 30000) & (df['experience'] > 4), ['employee_id', 'name']]

   employee_id      name
4            4  Vanshika

### df.at(row, column)

In [28]:
df.at[0, 'pay']

np.int64(23000)

In [29]:
df.loc[2].at['name']

'Amrit'

## Setting values

In [30]:
df2 = df.copy()
df2.head()

   employee_id       name  gender  experience    pay
0            0      Rahul    Male           2  23000
1            1  Vaishnavi  Female           3  27000
2            2      Amrit    Male           1  17000
3            3       Ravi    Male           4  36000
4            4   Vanshika  Female           7  64000

In [31]:
df2.at[2, 'pay'] = 100000
df2.loc[2]

employee_id         2
name            Amrit
gender           Male
experience          1
pay            100000
Name: 2, dtype: object

In [32]:
df2.loc[:,'name'] = "John"

df2.head()

   employee_id  name  gender  experience     pay
0            0  John    Male           2   23000
1            1  John  Female           3   27000
2            2  John    Male           1  100000
3            3  John    Male           4   36000
4            4  John  Female           7   64000

### WHERE operation with setting

In [33]:
df2.loc[(df2['pay'] > 30000) & (df2['gender'] == 'Male'), 'name'] = "David"
df2.head()

   employee_id   name  gender  experience     pay
0            0   John    Male           2   23000
1            1   John  Female           3   27000
2            2  David    Male           1  100000
3            3  David    Male           4   36000
4            4   John  Female           7   64000

In [34]:
df2.loc[(df2.loc[:, 'pay'] > 30000) & (df2.loc[:, 'gender'] == 'Male'), 'name']

2    David
3    David
Name: name, dtype: object

In [35]:
df2.loc[(df2.loc[:, 'pay'] > 30000) & (df2.loc[:, 'gender'] == 'Male'), 'name'] = "Hari"
df2.head()

   employee_id  name  gender  experience     pay
0            0  John    Male           2   23000
1            1  John  Female           3   27000
2            2  Hari    Male           1  100000
3            3  Hari    Male           4   36000
4            4  John  Female           7   64000

In [36]:
df2['experience']

0    2
1    3
2    1
3    4
4    7
Name: experience, dtype: int64

In [37]:
df2.loc[:, 'experience']

0    2
1    3
2    1
3    4
4    7
Name: experience, dtype: int64

## Missing Data

In [38]:
df.head()

   employee_id       name  gender  experience    pay
0            0      Rahul    Male           2  23000
1            1  Vaishnavi  Female           3  27000
2            2      Amrit    Male           1  17000
3            3       Ravi    Male           4  36000
4            4   Vanshika  Female           7  64000

In [39]:
df2 = df.copy()
df2.at[3, 'gender'] = np.nan

In [40]:
df2.isna()

   employee_id   name  gender  experience    pay
0        False  False   False       False  False
1        False  False   False       False  False
2        False  False   False       False  False
3        False  False    True       False  False
4        False  False   False       False  False

In [41]:
df2.notna()

   employee_id  name  gender  experience   pay
0         True  True    True        True  True
1         True  True    True        True  True
2         True  True    True        True  True
3         True  True   False        True  True
4         True  True    True        True  True

In [42]:
df2.dropna(how="any", axis=0, inplace=False, ignore_index=0)

   employee_id       name  gender  experience    pay
0            0      Rahul    Male           2  23000
1            1  Vaishnavi  Female           3  27000
2            2      Amrit    Male           1  17000
4            4   Vanshika  Female           7  64000

In [43]:
df2.fillna(value="Male")

   employee_id       name  gender  experience    pay
0            0      Rahul    Male           2  23000
1            1  Vaishnavi  Female           3  27000
2            2      Amrit    Male           1  17000
3            3       Ravi    Male           4  36000
4            4   Vanshika  Female           7  64000

## Merge

In [44]:
df_left = pd.DataFrame({
    "id" : np.arange(7, 12, dtype='int8'),
    "name" : ["Rahul", "Ravi", "Mahesh", "Sonu", "Prasad"],
    "age" : [12, 27, 54, 28, 79]
})

df_right = pd.DataFrame({
    "id" : np.arange(7, 13, dtype='int8'),
    "occupation" : ['Student', 'Electrician', 'Farmer', 'Engineer', 'Retired', 'Military'],
    "location" : ['Mumbai', "Delhi", 'Jabalpur', "Pune", "Bhopal", 'Kashmir'],
    "married" : [False, True, True, False, True, True]
})

In [45]:
df_merged = pd.merge(df_left, df_right, on="id")
df_merged

   id    name  age   occupation  location  married
0   7   Rahul   12      Student    Mumbai    False
1   8    Ravi   27  Electrician     Delhi     True
2   9  Mahesh   54       Farmer  Jabalpur     True
3  10    Sonu   28     Engineer      Pune    False
4  11  Prasad   79      Retired    Bhopal     True

### Concat

In [46]:
piece_1 = df[:2]
piece_2 = df[2:4]

pieces = [piece_2, piece_1]
df3 = pd.concat(pieces)
df3[0:3]

   employee_id   name gender  experience    pay
2            2  Amrit   Male           1  17000
3            3   Ravi   Male           4  36000
0            0  Rahul   Male           2  23000

## Grouping
- __Splitting__ the data into groups based on some criteria
- __Applying__ a function to each group independently
- __Combining__ the results into a data structure

In [47]:
df.head()

   employee_id       name  gender  experience    pay
0            0      Rahul    Male           2  23000
1            1  Vaishnavi  Female           3  27000
2            2      Amrit    Male           1  17000
3            3       Ravi    Male           4  36000
4            4   Vanshika  Female           7  64000

With sort=False the order among group-keys follows the order of appearance of the keys in the original dataframe

In [48]:
grouped = df.groupby("gender", observed=True, sort=False).mean('pay')
grouped.head()

        employee_id  experience           pay
gender
Male       1.666667    2.333333  25333.333333
Female     2.500000    5.000000  45500.000000

In [49]:
# grouped = df.groupby("gender", observed=True, sort=False)[['experience', 'pay']].mean('pay')
grouped = df.groupby("gender", observed=True, sort=False).mean('pay')[['experience', 'pay']]
grouped

        experience           pay
gender
Male      2.333333  25333.333333
Female    5.000000  45500.000000

__We only had unique values but our indexes were duplicates. So data was grouped together on the basis of same indexes.__<br></br>
If a non-unique index is used as the group key in a groupby operation, all values for the same index value will be considered to be in one group and thus the output of aggregation functions will only contain unique index values

In [50]:
index = 1, 2, 3, 1, 2, 3, np.nan
data = pd.DataFrame([11, 12, 13, 14, 15, 16, 17], index = index, columns=['values'])
grouped = data.groupby('values', level=0, sort=True, dropna=True).sum()
grouped

     values
1.0      25
2.0      27
3.0      29

## Importing data
- pd.read_csv('filename')
- df.to_csv('enterFileName.csv')
- pd.read_excel('filename', sheet_name='sheet-name')
- df.to_excel('foo.xlsx', sheet_name='sheet-name')

### csv

In [52]:
pathname = "/workspaces/codespaces-jupyter/data/data7.csv"
df = pd.read_csv(pathname)
df.tail()

       Responder_id  Age
79205         87352   59
79206         87386   21
79207         87739   25
79208         88212   40
79209         88863   18